[default]
# Application settings
DEBUG = false
SECRET_KEY = "your-secret-key-here-change-in-production"

# Database
DATABASE_URL = "sqlite+aiosqlite:///./speed_dating.db"
DATABASE_ECHO = false

# Server settings
HOST = "127.0.0.1"
PORT = 8000
ALLOWED_ORIGINS = ["http://localhost:3000", "http://localhost:8000"]

# QR Code settings
QR_CODE_BASE_URL = "http://localhost:8000"

# PDF Badge settings
PDF_BADGES_PER_PAGE = 35

# Documentation settings
DOCS_DIRECTORY = "docs"
AUTO_GENERATE_DOCS = true

# Email/SMTP settings (optional - for password reset emails)
# Uncomment and configure for email functionality
# SMTP_HOST = "smtp.gmail.com"
# SMTP_PORT = 587
# SMTP_USERNAME = "your-email@gmail.com"
# SMTP_PASSWORD = "your-app-password"
# SMTP_TLS = true
# SMTP_FROM_EMAIL = "noreply@yourdomain.com"

[development]
DEBUG = true
DATABASE_ECHO = true
ALLOWED_ORIGINS = ["*"]

[production]
DEBUG = false
DATABASE_ECHO = false
# Set proper production values in .secrets.toml